#!/usr/bin/env python3
"""Regenerate docs/DEVICES.md from the registry.

Keeping the reference table generated rather than hand-maintained means it
can never drift from the specs the simulator actually uses.

Usage:  python3 docs/gen_devices.py > docs/DEVICES.md
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from flowgpu.hardware.registry import DATAFLOW, GPUS, make_device
from flowgpu.power import calibrate
from flowgpu.units import fmt_bw, fmt_bytes, fmt_flops
from flowgpu.workload.models import get_model, list_models


def main():
    print("# Device and model reference\n")
    print("*Auto-generated by `python3 docs/gen_devices.py`. Every row carries a")
    print("confidence tag: `vendor` (datasheet), `paper` (peer-reviewed),")
    print("`press` (announcement), `derived` (computed from published figures),")
    print("`estimate` (inferred — do not quote as a vendor spec).*\n")
    print("All FLOPS are **dense** unless a note says otherwise; vendor figures")
    print("quoted with 2:4 structured sparsity have been halved.\n")

    print("## GPUs\n")
    print("| device | vendor | nm | yr | SMs | bf16 | int8 | memory | mem BW | L2 | TDP | conf |")
    print("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for n in sorted(GPUS):
        d = make_device(n)
        l2 = d.level("l2")
        print(f"| `{n}` | {d.vendor} | {d.process_nm:g} | {d.year} | {d.n_units} | "
              f"{fmt_flops(d.compute.peak_for('bf16'))} | {fmt_flops(d.compute.peak_for('int8'))} | "
              f"{fmt_bytes(d.capacity)} | {fmt_bw(d.main_memory.bandwidth)} | "
              f"{fmt_bytes(l2.capacity) if l2 else '-'} | {d.energy.tdp:.0f} W | "
              f"{d.extra.get('confidence','')} |")

    print("\n### GPU sources\n")
    for n in sorted(GPUS):
        d = make_device(n)
        print(f"- **`{n}`** — {d.extra.get('source','')}"
              + (f"  \n  {d.notes}" if d.notes else ""))

    print("\n## Brain-inspired many-core dataflow chips\n")
    print("| device | vendor | arch | nm | yr | cores | SRAM/core | SRAM total | "
          "SRAM BW | bf16 | NoC bisect | chip-to-chip | board-to-board | DRAM | TDP | conf |")
    print("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for n in sorted(DATAFLOW):
        d = make_device(n)
        dram = d.level("dram") or d.level("hbm")
        print(f"| `{n}` | {d.vendor} | {d.arch} | {d.process_nm:g} | {d.year} | {d.n_cores} | "
              f"{fmt_bytes(d.sram_per_core)} | {fmt_bytes(d.total_sram)} | {fmt_bw(d.total_sram_bw)} | "
              f"{fmt_flops(d.compute.peak_for('bf16'))} | {fmt_bw(d.noc.bisection_bandwidth)} | "
              f"{fmt_bw(d.inter_chip_bw)} | {fmt_bw(d.inter_board_bw)} | "
              f"{(fmt_bytes(dram.capacity)+' @ '+fmt_bw(dram.bandwidth)) if dram else 'none'} | "
              f"{d.energy.tdp:.0f} W | {d.extra.get('confidence','')} |")

    print("\n### SRAM die-area plausibility\n")
    print("SRAM array area implied by the quoted capacity and process node")
    print("(6T bitcell + 1.35x array/periphery overhead), against an ~800 mm2")
    print("reticle. A part needing more than ~0.65 reticles of SRAM alone is a")
    print("multi-die package whether or not the datasheet says so.\n")
    print("| device | SRAM | node | SRAM area | reticles | single die? |")
    print("|---|---|---|---|---|---|")
    for n in sorted(DATAFLOW):
        d = make_device(n)
        c = d.die_area_check()
        print(f"| `{n}` | {fmt_bytes(d.total_sram)} | {c['node_nm']:g} nm | "
              f"{c['sram_area_mm2']:.1f} mm2 | {c['dies_needed']:.2f} | "
              f"{'yes' if c['plausible'] else '**no**'} |")

    print("\n### Dataflow sources\n")
    for n in sorted(DATAFLOW):
        d = make_device(n)
        print(f"- **`{n}`** — {d.extra.get('source','')}"
              + (f"  \n  {d.notes}" if d.notes else ""))

    from flowgpu.power import load_eda_db
    db = load_eda_db()
    eda = (db or {}).get("default")
    print("\n## Calibrated energy coefficients\n")
    print("Produced by `flowgpu.power.model.calibrate`. Apportionment comes")
    if eda:
        print(f"from **measured Synopsys DC + PrimeTime PX runs** "
              f"(`{eda.get('run_id')}`, activity "
              f"`{eda.get('activity','?')}`); absolute scale is anchored to")
    else:
        print("from the technology table; absolute scale is anchored to")
    print("each device's TDP. Off-chip DRAM energy is **not** rescaled --")
    print("3.5 pJ/bit for HBM3 is interface physics, not a free parameter.\n")
    print("| device | source | bf16 pJ/FLOP | int8 pJ/FLOP | SRAM pJ/B | "
          "L2 pJ/B | DRAM pJ/B | NoC pJ/B/hop | static W |")
    print("|---|---|---|---|---|---|---|---|---|")
    for n in ["h100_sxm", "b200_sxm", "a100_80gb_sxm", "iluvatar_bi_v100",
              "ascend_910b", "groq_lpu_v1", "ipu_gc200", "lynxi_ka200",
              "lynxi_hp300_proj", "cerebras_wse3"]:
        d = make_device(n)
        calibrate(d, eda=eda)
        j = d.energy.j_per_byte
        sram = j.get("sram") or j.get("smem")
        print(f"| `{n}` | {d.energy.source} | "
              f"{d.energy.j_per_flop.get('bf16',0)*1e12:.3f} | "
              f"{d.energy.j_per_flop.get('int8',0)*1e12:.3f} | "
              f"{(sram or 0)*1e12:.2f} | {(j.get('l2') or 0)*1e12:.2f} | "
              f"{(j.get('hbm') or j.get('dram') or 0)*1e12:.2f} | "
              f"{d.energy.j_per_byte_noc*1e12:.3f} | {d.energy.static_power:.0f} |")

    print("\n## Models\n")
    print("| model | family | L | d | total params | active | experts | top-k | "
          "attn | KV/token | source |")
    print("|---|---|---|---|---|---|---|---|---|---|---|")
    for fam, names in list_models().items():
        for n in names:
            m = get_model(n)
            if fam in ("llm", "vlm"):
                print(f"| `{n}` | {fam} | {m.n_layers} | {m.d_model} | "
                      f"{m.total_params()/1e9:.1f} B | {m.active_params()/1e9:.1f} B | "
                      f"{m.n_experts or '-'} | {m.n_active_experts or '-'} | "
                      f"{'MLA' if m.is_mla else 'GQA'} | "
                      f"{m.kv_bytes_per_token()/1024:.1f} KiB | "
                      f"{m.extra.get('source','')} |")
            else:
                e = m.extra
                print(f"| `{n}` | {fam} | - | - | - | - | - | - | "
                      f"{e.get('kind', e.get('arch',''))} | - | {e.get('source','')} |")
    return 0


if __name__ == "__main__":
    sys.exit(main())
